import java.sql.*;
import java.util.ArrayList;

public class AdminPage extends javax.swing.JPanel {
    public static SQLConn sqlconn;
    
    public AdminPage() {
        initComponents();
        sqlconn = new SQLConn();
    }
    
    public AdminPage(SQLConn sql){
        initComponents();
        sqlconn = sql; //use the global connector instead of creating a new ones 
        System.out.println("init component should've run");
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_tableNames = new javax.swing.JList<>();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_tuples = new javax.swing.JList<>();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Page");
        jLabel1.setToolTipText("");

        lst_tableNames.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lst_tableNames.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CREDITCARD", "DIRECTOR", "GUESTINFO", "MANAGER_", "MEMBERTYPE", "MOVIE", "MOVIEHISTORY", "MOVIERESPONSES", "MOVIEREVIEWS", "MOVIETHREAD", "MOVIETIMES", "MOVIETIMES2", "POSITIONS", "REGISTERINFO", "SCHEDULE", "SCHEDULE2", "SCHEDULE3", "SCREEN", "STAFF", "STAFF2", "STAR_", "THEATRE", "THEATRERESPONSES", "THEATREREVIEWS", "THEATRETHREAD", "USER_" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_tableNames.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_tableNamesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lst_tableNames);

        btn_add.setText("Add");

        btn_update.setText("Update");

        btn_delete.setText("Delete");

        jScrollPane2.setViewportView(lst_tuples);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 417, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lst_tableNamesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_tableNamesValueChanged
        String newVal = lst_tableNames.getSelectedValue(); //name of a table
        ArrayList<String> strTuples = sqlconn.getAllTableValues(newVal);
        for(int i = 0; i<strTuples.size(); i++){
            System.out.println(strTuples.get(i));
        }
    }//GEN-LAST:event_lst_tableNamesValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lst_tableNames;
    private javax.swing.JList<String> lst_tuples;
    // End of variables declaration//GEN-END:variables
}
