
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

public class AdminFrame extends javax.swing.JFrame {
    public static SQLConn sqlconn;
    
    public AdminFrame() {
        initComponents();
        sqlconn = new SQLConn();
    }
    
    public AdminFrame(SQLConn sql){
        initComponents();
        sqlconn = sql;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Admin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_tableNames = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_tuples = new javax.swing.JList<>();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        lbl_colnames = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 550));

        lbl_Admin.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_Admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Admin.setText("Admin Page");

        lst_tableNames.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CREDITCARD", "DIRECTOR", "GUESTINFO", "MANAGER_", "MEMBERTYPE", "MOVIE", "MOVIEHISTORY", "MOVIERESPONSES", "MOVIEREVIEWS", "MOVIETHREAD", "MOVIETIMES", "MOVIETIMES2", "POSITIONS", "REGISTERINFO", "SCHEDULE", "SCHEDULE2", "SCHEDULE3", "SCREEN", "STAFF", "STAFF2", "STAR_", "THEATRE", "THEATRERESPONSES", "THEATREREVIEWS", "THEATRETHREAD", "USER_" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_tableNames.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_tableNamesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lst_tableNames);

        jScrollPane2.setViewportView(lst_tuples);

        btn_add.setText("Add");

        btn_update.setText("Update");

        btn_delete.setText("Delete");

        lbl_colnames.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_colnames.setText("Column Names");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(lbl_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 375, Short.MAX_VALUE))
                    .addComponent(lbl_colnames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_colnames, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lst_tableNamesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_tableNamesValueChanged
        String newVal = lst_tableNames.getSelectedValue(); //name of a table
        
        //update the column names (lbl_colnames)
        String colNames = sqlconn.getColNames(newVal);
        lbl_colnames.setText(colNames);
        
        
        //Update The Output List (lst_tuples)
        DefaultListModel newModel = new DefaultListModel();
        
        ArrayList<String> strTuples = sqlconn.getAllTableValues(newVal);
        for(int i = 0; i<strTuples.size(); i++){
            //System.out.println(strTuples.get(i));
            newModel.addElement(strTuples.get(i));
        }
        
        lst_tuples.setModel(newModel); //update the output list
        
    }//GEN-LAST:event_lst_tableNamesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Admin;
    private javax.swing.JLabel lbl_colnames;
    private javax.swing.JList<String> lst_tableNames;
    private javax.swing.JList<String> lst_tuples;
    // End of variables declaration//GEN-END:variables
}