--Wei Mei, Devanshu Bharel, Alex Nicoara
DROP TABLE Theatre CASCADE CONSTRAINTS;
DROP TABLE movietimes CASCADE CONSTRAINTS;
DROP TABLE movie CASCADE CONSTRAINTS;
DROP TABLE star_ CASCADE CONSTRAINTS;
DROP TABLE director CASCADE CONSTRAINTS;
DROP TABLE screen CASCADE CONSTRAINTS;
DROP TABLE theatrereviews CASCADE CONSTRAINTS;
DROP TABLE moviereviews CASCADE CONSTRAINTS;
DROP TABLE membertype CASCADE CONSTRAINTS;
DROP TABLE creditcard CASCADE CONSTRAINTS;
DROP TABLE user_ CASCADE CONSTRAINTS;
DROP TABLE guestinfo CASCADE CONSTRAINTS;
DROP TABLE registerinfo CASCADE CONSTRAINTS;
DROP TABLE moviehistory CASCADE CONSTRAINTS;
DROP TABLE moviethread CASCADE CONSTRAINTS;
DROP TABLE movieresponses CASCADE CONSTRAINTS;
DROP TABLE theatrethread CASCADE CONSTRAINTS;
DROP TABLE theatreresponses CASCADE CONSTRAINTS;
DROP TABLE positions CASCADE CONSTRAINTS;
DROP TABLE staff CASCADE CONSTRAINTS;
DROP TABLE manager_ CASCADE CONSTRAINTS;
DROP TABLE schedule CASCADE CONSTRAINTS;











