/* When a user purchases a ticket for a certain theatre, ADD the ticket value of the theatre
   to the total sales of the theatre. Just makes life a lot easier. */
   
-- AUTHORIZATION AND PRIVILEGES
-- STILL UPDATING

-- GENERAL PROCESSES
-- STILL UPDATING

-- QUERIES:
/* #1. Display the 3 most recent discussions/comments from a specific discussion thread 
       NOTE: THE USER CAN SPECIFY WHICH THREAD (BASED ON ENTERING THE THREAD ID) AND IF ITS FROM THEATRE THREADS OR MOVIE THREADS 
	   NOTE2: ALSO PRINT THE INITIAL THREAD CONTENT ABOVE THE 3 MOST RECENT COMMENTS. (THE HIGHEST COMMENT WILL BE THE LEAST RECENT)*/
	   
-- FROM THEATRERESPONSES, WHERE THE THREADID is 6
SELECT THREADID, USER_, CONTENT_
FROM (SELECT * FROM THEATRERESPONSES WHERE THREADID = 6 ORDER BY ID ASC)
WHERE ROWNUM <= 3;

-- FROM MOVIERESPONSES, WHERE THE THREADID is 6
SELECT THREADID, USER_, CONTENT_
FROM (SELECT * FROM MOVIERESPONSES WHERE THREADID = 6 ORDER BY ID ASC)
WHERE ROWNUM <= 3;

/* #7. Display the theatre that has the most ticket sales */
SELECT ADDRESS, ZIP, OWNER_
FROM (SELECT * FROM THEATRE ORDER BY SALES DESC)
WHERE ROWNUM = 1;
